version: "3.10"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  lotr-api:
    build: .
    volumes:
      - .:/code

    ports:
      - "8000:8000"

    env_file: .env

    depends_on:
      - db