# Generated by Django 5.0.4 on 2024-04-30 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.CharField(max_length=100, unique=True)),
                ("character_name", models.CharField(max_length=100)),
                ("wikiUrl", models.CharField(max_length=100)),
                ("race", models.CharField(max_length=100)),
                ("birth", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("death", models.CharField(max_length=100)),
                ("hair", models.CharField(max_length=100)),
                ("height", models.CharField(max_length=100)),
                ("realm", models.CharField(max_length=100)),
                ("spouse", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
