# Generated by Django 5.0.4 on 2024-04-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="birth",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="death",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="gender",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="hair",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="height",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="race",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="realm",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="spouse",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
