# Generated by Django 5.0.4 on 2024-05-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_character_wikiurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='_id',
            field=models.CharField(max_length=100),
        ),
    ]
